# Generated by Django 2.2.4 on 2019-11-11 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('idFamily', models.AutoField(primary_key=True, serialize=False)),
                ('familyName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('familyPhotos', models.CharField(max_length=5000)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
