# Generated by Django 2.2.2 on 2019-11-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('idRecord', models.AutoField(primary_key=True, serialize=False)),
                ('familyName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
                ('recordPhotoPath', models.CharField(max_length=500)),
                ('dateRecord', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
